### ISSUE TITLE
Question: Defining Data Models as Ontologies

### ISSUE THREAD

**Issue by Spydernaz** [OTRF/OSSEM#101]
Hey guys,

I see that you have defined the Common Data Model as a YAML to help with readability etc, but I was wondering if it would be worthwhile to describe these models as an ontology. It might also help describe the relationships between elements. I was already looking at describing a series of ontologies that relate attacks and the sort of data you would require to detect it. Would this be something of interest ?

**Comment by Cyb3rPandaH** [comment]
Hey @Spydernaz , thank you for your question!! We would like to share ideas with you about describing data models as an Ontology within OSSEM. Please join our discord server (https://bit.ly/OTRDiscord) so we can continue the conversation in the ossem channel. We are going to share main updates about this topic through this issue, but have conversations in Discord if that works for you. Thank you!

**Comment by Cyb3rPandaH** [comment]
We are going to open more specific issues regarding OSSEM Ontology 🍻
