### ISSUE TITLE
Typographical Error

### ISSUE THREAD

**Issue by evandrix** [OTRF/OSSEM#110]
https://github.com/OTRF/OSSEM/blob/master/source/detection_data_model/tables/process-object-relationships.yml#L121
extra whitespace: ~~relationship: bound _to~~ relationship: bound_to

**Comment by Cyb3rWard0g** [comment]
Hello @evandrix ! Thank you for letting us know. We have been updating the structure of the project and now each branch of OSSEM (data dictionaries, detection model and common data model) has its own Github submodule. 

I believe what you were referring to is this relationship correct?

https://github.com/OTRF/OSSEM-DM/blob/main/relationships/process_bound_to_port.yml

From now own, we are going keep all relationship names with spaces and they can be processed programmatically and add `_` underscores or to anything with it :) 

We would love to get your feedback .  Feel free to reopen this issue if necessary.
